
openapi: 3.0.0
info:
  title: Сервіс Статей
  description: Написати сервіс статей (2000 символів). Статті є публічними для всіх, зареєстровані користувачі можуть редагувати статтю та очікувати на схвалення її модераторами (користувачі із більшими правами). Передбачити варіант редагування, коли стаття на розгляді модератором, а інший користувач її теж редагує. Модератори мають бачити статті, які очікують їх схвалення
  version: 0.0.1
  contact:
    url: "https://github.com/salabay777/pp_project"
servers:
- url: /
tags:
- name: article
  description: Operations about articles
- name: user
  description: Users functions and operations about user
- name: moderator
  description: Moderators functions
- name: updateArticle
  description: Operations about versions of article
paths:  
  /updateArticle/{ArticleId}/{UserId}/{EditedBody}:
    post:
      tags:
      - updateArticle
      summary: Edit created article
      operationId: EditArticle
      parameters:
      - name: ArticleId
        in: path
        description: ID of Article to found
        required: true
        schema:
          type: integer
          format: int64
      - name: UserId
        in: path
        description: User Id who edit article
        required: true
        schema:
          type: integer
          format: int64
      - name: EditedBody
        in: path
        description: New version of article
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content: {}
        404:
          description: Entered ID does not exist
          content: {}
      security:
      - ApiKeyAuth: []
  /updateArticle/{ArticleId}:
    get:
      tags:
      - updateArticle
      summary: Get versions of article
      parameters:
      - name: ArticleId
        in: path
        description: ID of Article to found
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Article'
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        404:
          description: Entered ID does not exist 
      security:
      - ApiKeyAuth: [] 
  /updateArticle/{ModeratorKey}/{ArticleId}/{ArticleVersion}:
    put:
      tags:
      - updateArticle
      summary: Accept article
      parameters:
      - name: api_key
        in: header
        schema:
          type: string
      - name: ArticleId
        in: path
        description: Article ID to delete
        required: true
        schema:
          type: integer
          format: int64
      - name: ModeratorKey
        in: path
        description: Moderators key for accept or delete article
        required: true
        schema:
          type: string
      - name: ArticleVersion
        in: path
        description: Article version to accept
        required: true
        schema:
          type: string
      responses:
        200:
          description:  Article succeful accepted 
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/Article'
            applicationUser/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
               schema:
                $ref: '#/components/schemas/Article'
            applicationUser/xml:
               schema:
                $ref: '#/components/schemas/User'
        404:
          description: Entered ID does not exist
          content: {}
        403:
          description: Invalid moderator key 
          content: {}
      security:
      - ApiKeyAuth: []
  /article:
    post:
      tags:
      - article
      summary: Add a new article
      operationId: addArticle
      requestBody:
        description: Create a new article
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
          application/xml:
            schema:
              $ref: '#/components/schemas/Article'
        required: true
      responses:
        405:
          description: Name wasn't defined
          content: {}
        406:
          description: Body wasn't defined
          content: {}
        403:
          description: Selected ID is already in use
      security:
      - ApiKeyAuth: []
      x-codegen-request-body-name: body
  /article/{ArticleId}:
    get:
      tags:
      - article
      summary: Get article to read
      parameters:
      - name: ArticleId
        in: path
        description: ID of Article to found
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Article'
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        404:
          description: Entered ID does not exist 
  /article/{ModeratorKey}/{ArticleId}:
    delete:
      tags:
      - article
      summary: Delete a Article
      operationId: deleteArticle
      parameters:
      - name: api_key
        in: header
        schema:
          type: string
      - name: ArticleId
        in: path
        description: Article ID to delete
        required: true
        schema:
          type: integer
          format: int64
      - name: ModeratorKey
        in: path
        description: Moderators key for accept or delete article
        required: true
        schema:
          type: string
      responses:
        404:
          description: Entered ID does not exist
          content: {}
        403:
          description: Invalid moderator key 
          content: {}
      security:
      - ApiKeyAuth: []
  /user:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the unlogged in user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        400:
          description: Invalid username/password supplied
          content: {}
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: {}
  /user/{userId}:
    get:
      tags:
      - user
      summary: Get user by user id
      operationId: getUserByID
      parameters:
      - name: userId
        in: path
        description: 'The name that needs to be fetched. Use user1 for testing. '
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid username supplied
          content: {}
        404:
          description: User not found
          content: {}
      security:
      - ApiKeyAuth: []
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user
      operationId: deleteUser
      parameters:
      - name: userId
        in: path
        description: The name that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        400:
          description: Invalid username supplied
          content: {}
        404:
          description: User not found
          content: {}
      security:
      - ApiKeyAuth: [] 
  /moderator/{ModeratorKey}:
    post:
      tags:
      - moderator
      summary: Create moderator
      description: This can only be done by the logged in user.
      operationId: createModerator
      parameters:
      - name: ModeratorKey
        in: path
        description: Moderators key for accept or delete article
        required: true
        schema:
          type: string
      requestBody:
        description: Created user object
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Moderator'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body
      security:
      - ApiKeyAuth: []
  /moderator/login/{ModeratorKey}:
    get:
      tags:
      - moderator
      summary: Logs moderator into the system
      operationId: loginModerator
      parameters:
      - name: ModeratorKey
        in: path
        description: You can login as a moderator only with a key
        required: true
        schema:
          type: string
      - name: moderatorname
        in: query
        description: The moderator name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        400:
          description: Invalid username/password supplied
          content: {}
      security:
      - ApiKeyAuth: []
  /moderator/logout/{ModeratorKey}:
    get:
      tags:
      - moderator
      summary: Logs out current logged in moderator session
      operationId: logoutModerator
      parameters:
      - name: ModeratorKey
        in: path
        description: You can logout as a moderator only with a key
        required: true
        schema:
          type: string
      responses:
        default:
          description: successful operation
          content: {}
      security:
      - ApiKeyAuth: []
components:
  schemas:
    Moderator:
      type: object
      properties:
        id:
          type: integer
          format: int64
        moderatorname:
          type: string
          example: moder
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Price
        email:
          type: string
          example: moderator@email.com
        password:
          type: string
          example: somepassword
        moderatorkey:
          type: string
          example: D9YH63Lk3Vx7drr
      xml:
        name: Moderator
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          example: user
        firstName:
          type: string
          example: Francic
        lastName:
          type: string
          example: Underwood
        email:
          type: string
          example: user@email.com
        password:
          type: string
          example: anothersomepassword

      xml:
        name: User
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Einstein's theory of relativity
        body:
          type: string
          example: Something about the theory of relativity
        version:
          type: string
          example: 0.0.1
      xml:
        name: Article
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: API-Key
      in: header